jesec/flood

- Dockerfile
Provided any flood_secret, for build time, to allow build docker correctly.
Workaround to make docker build. I know its not the cleanest solution, not sure how to handle it better now ? Maybe remove || CHANGE_ME in config, and do some during init validation in JS ? I'm not JS coder so won't be able to help with that.
https://github.com/jesec/flood/issues/22
> Dockerfile: provide a secret to allow build to proceed

- client/src/javascript/actions/TorrentActions.ts
- client/src/javascript/components/general/form-elements/FilesystemBrowserTextbox.tsx
- client/src/javascript/components/modals/add-torrents-modal/AddTorrentsByFile.tsx
- client/src/javascript/components/modals/add-torrents-modal/AddTorrentsByURL.tsx
- client/src/javascript/components/torrent-list/TorrentListContextMenu.tsx
- client/src/javascript/components/torrent-list/TorrentListRow.tsx
- client/src/javascript/constants/TorrentContextMenuActions.ts
- client/src/javascript/i18n/strings.compiled.json
- client/src/javascript/i18n/strings.json
- server/routes/api/torrents.ts
- server/services/Transmission/clientGatewayService.ts
- server/services/feedService.ts
- server/services/interfaces/clientGatewayService.ts
- server/services/qBittorrent/clientGatewayService.ts
- server/services/qBittorrent/clientRequestManager.ts
- server/services/rTorrent/clientGatewayService.ts
- server/services/rTorrent/constants/methodCallConfigs/torrentList.ts
- shared/constants/defaultFloodSettings.ts
- shared/schema/api/torrents.ts
- shared/types/Torrent.ts
- shared/types/api/torrents.ts
Client:
- rTorrent: requires "d.down.sequential(.set)" commands, see https://github.com/jesec/rtorrent/commit/bd904e366367cb9cbe007381089eea066253c9e9
- qBittorrent: supported
- Transmission: rejected, see [https://trac.transmissionbt.com/ticket/452](https://trac.transmissionbt.com/ticket/452)
Drawbacks:
- https://wiki.vuze.com/w/Sequential_downloading_is_bad
Benefits:
1. Sequential downloading helps with I/O performance and lowers resource consumption and cost of hardware. It enables predictable I/O patterns and efficient caching. My hard disk is really noisy while downloading a torrent. But with sequential downloading, it does not make a sound. Speed is much better as well. Sequential I/O patterns also eliminate disk fragmentation problem that damages performance/lifespan of hard disks …
> feature: add support for sequential download

- client/src/javascript/actions/TorrentActions.ts
- client/src/javascript/components/torrent-list/TorrentListContextMenu.tsx
- client/src/javascript/constants/TorrentContextMenuActions.ts
- client/src/javascript/i18n/strings.compiled.json
- client/src/javascript/i18n/strings.json
- server/routes/api/torrents.ts
- server/services/Transmission/clientGatewayService.ts
- server/services/feedService.ts
- server/services/interfaces/clientGatewayService.ts
- server/services/qBittorrent/clientGatewayService.ts
- server/services/qBittorrent/clientRequestManager.ts
- server/services/rTorrent/clientGatewayService.ts
- server/services/rTorrent/constants/methodCallConfigs/torrentList.ts
- shared/constants/defaultFloodSettings.ts
- shared/schema/api/torrents.ts
- shared/types/Torrent.ts
- shared/types/api/torrents.ts
https://www.bittorrent.org/beps/bep_0016.html
Client:
- rTorrent: ~supported, https://github.com/rakshasa/rtorrent/wiki/Using-initial-seeding~ not exposed to RPC interface, requires https://github.com/jesec/rtorrent/commit/657089d438f917714c2386c28ce9d01a6e6a2737. 
- qBittorrent: supported, https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#set-super-seeding
- Transmission: not supported, see https://trac.transmissionbt.com/ticket/1691
> feature: support initial seeding (aka superseeding)

- README.md
I was trying to get Flood running since 1 week and everything was working except the .torrent upload. It wasn't really clear in the documentation that the temp folder of Flood needed to be accessible to rTorrent in order for it to add torrents (I thought torrent data was sent with the request entirely). So I modified the Readme to be totally clear on that.
> Clarify that Flood's torrent upload is also reliant on the "same path rule"

- client/src/javascript/components/general/Tooltip.tsx
- client/src/javascript/components/sidebar/SidebarFilter.tsx
Add support for vimium keyboard navigation and screen readers
* Add menuitem role to SidebarFilter li
* Add button role to Tooltip div
Adds `role="menuitem"` to clickable `li` elements in SidebarFilter and `role="button" tabIndex={0}` to `div` elements in Tooltip
https://github.com/Flood-UI/flood/issues/885
> Add role attribute to clickable elements

- server/services/rTorrent/clientGatewayService.ts
- server/services/rTorrent/clientRequestManager.ts
- server/services/rTorrent/util/scgiUtil.ts
Preliminary tests: (compared to XMLRPC)
2x performance, 15% lower total CPU time in rTorrent process, 33% lower total CPU time in Node.js process. Note that there are 28000+ entries, so it is natural to take seconds to complete the request. Additionally, current implementation on the rTorrent side uses nlohmann's `JSON for Modern C++`, which is the easiest to use but it is not one of the most "High Performance" JSON library. Some JSON libraries feature up to [8x performance](https://github.com/miloyip/nativejson-benchmark#stringify-time) over nlohmann/json.
> rTorrent: use JSON-RPC when available

- client/src/sass/components/_modals.scss
Regarding the width of today's screens, it appears more comfortable to have a slightly larger torrent info modal.
I think it would be a nice to have UX improvement.
None.
From :
https://i.imgur.com/WehobrX.png
To :
https://i.imgur.com/8DR2U5x.png
UX improvement.
> Larger torrent infos modal

- client/src/javascript/actions/UIActions.ts
- client/src/javascript/components/torrent-list/TorrentList.tsx
- client/src/javascript/stores/TorrentStore.ts
After the user selected a torrent, user can use `CMD-A` or `CTRL-A` to select all torrents. Click one torrent to deselect all. Very useful for bulk editing large collection of torrents.
For https://github.com/jesec/flood/discussions/122#discussioncomment-480117
> client: add CMD-A, CTRL-A to select all torrents

- distribution/containers/Dockerfile.release
- distribution/containers/Dockerfile.rtorrent
Small change here. I created an `ENTRYPOINT` with [tini](https://github.com/krallin/tini) and updated the `CMD` in the `Dockerfile`s. tini is already included in the `Docker` CRI, however some people (like me) use a different CRI like `containerd` or `cri-o` where we don't have access to an `--init` flag. 
`tini` also has other benefits as described in this [Github issue](https://github.com/krallin/tini/issues/8#issuecomment-146135930).
Container image change
> feat: add tini to container images

- distribution/containers/Dockerfile.release
- distribution/containers/Dockerfile.rtorrent
I did not think of the ramifications of moving flood from the entrypoint to the command. Keeping it in the entrypoint should mean it will work the way the documentation expects it too.
Let me know if you want me to move the other flags to the entrypoint as well or if they are expected to be defaults we could leave them out.
Sorry!
> fix: flood entrypoint in container images

- README.md
- distribution/containers/Dockerfile.distroless
- distribution/containers/Dockerfile.release
- distribution/containers/Dockerfile.rtorrent
This sets up the defaults in the docker container to use config from env instead of args
As discussed here https://github.com/jesec/flood/pull/261
> feat: use env instead of args in docker images

- server/services/qBittorrent/clientGatewayService.ts
I was getting a 500 on `GET /api/torrents/{hash}/metainfo`
By looking at the code, I guessed Flood wasn't able to find the torrent file.
Indeed, my qBittorent folder isn't the same as the one in the code:
```
qbt@sana ~> ll .local/share/data/
ls: cannot access '.local/share/data/': No such file or directory
qbt@sana ~> ll .local/share/qBittorrent/
total 164K
drwxr-xr-x 2 qbt qbt 144K Apr 10 00:44 BT_backup/
drwxr-xr-x 2 qbt qbt 4.0K Jan 24 19:27 GeoDB/
drwxr-xr-x 2 qbt qbt 4.0K Apr 10 00:33 logs/
drwxr-xr-x 3 qbt qbt 4.0K Mar 31 21:18 nova3/
drwxr-xr-x 3 qbt qbt 4.0K Jan 24 19:27 rss/
```
By looking at the qbt source code, it looks like the one hardcoded in Flood is the "legacy" one:
```cpp
// On Linux keep using the legacy directory ~/.local/share/data/ if it exists
const QString …
```
> server: qBittorent: fix getClientSessionDirectory on Linux

- README.md
Hey
I created [flood-api](https://github.com/sabersalv/flood-api), a JavaScript API wrapper for flood, with a clean footprint and a [beautiful API documentation](https://flood-api.netlify.app/).
Can you include it in the README? So that it can benefit everyone in the open-source community. 
Thanks
> doc: add flood-api, a JavaScript client library

- server/util/diskUsageUtil.ts
docker will mount some overlay fs, and get displayed when running `df -T`
```text
...
overlay         overlay   236937040   65102840 159728780   29% /var/lib/docker/overlay2/72e95b1a20e559eb6d8f10d888365f898bf5da17c09cd6d2ba3fe5c0aa7c22b5/merged
overlay         overlay   236937040   65102840 159728780   29% /var/lib/docker/overlay2/cef03d67bf64ff7addc78d7938dedd6a0dcb4943412e4a9bb5b7083507420b55/merged
```
this mount path should be omitted by diskUsage util.
No
No
> Skip docker overlayfs mount point

- server/services/feedService.ts
1. Edit a RSS rule calls `removeItem`, then `addRule`
2. `addRule` keep pushing rule into `this.rules`
https://github.com/jesec/flood/blob/6aac6486efbb360a24b6b8370156928cf5f6b910/server/services/feedService.ts#L181 
3. But `removeItem` does not remove rule from `this.rules`
4. That caused the problem, edit a rule may not work. When you edit the rule multpile times, `this.rules` becomes larger and larger, old rules are never get removed.
In the future, can create a new `editRule` api for simplication.
> fix: RSS feed rule edit

- .devcontainer/Dockerfile
- Dockerfile
- distribution/archlinux/Dockerfile.aur
- distribution/containers/Dockerfile.distroless
- distribution/containers/Dockerfile.release
- distribution/containers/Dockerfile.rtorrent
This PR adds the container registry (docker.io) to image references. This enables out-of-the-box support for podman.
> containers: add registry to image references

- client/src/sass/components/_loading-indicator.scss
This PR fixes the alignment of the middle bar of the loading indicator on the loading overlay and changes it to use flex instead of absolute positioning.
The indicator had a total height of 18px and in it three bars with a height of 3px each. This left 9px for margins split into 4px and 5px.
The indicator now has a height of 19px which leaves 10px for margins split evenly into 5px each.
> client: fix loading indicator bar alignment

- client/src/javascript/components/sidebar/SidebarFilter.tsx
- client/src/javascript/components/sidebar/StatusFilters.tsx
- client/src/javascript/components/sidebar/TagFilters.tsx
- client/src/javascript/components/sidebar/TrackerFilters.tsx
- client/src/javascript/stores/TorrentFilterStore.ts
- client/src/javascript/stores/TorrentStore.ts
- client/src/javascript/util/filterTorrents.ts
- shared/constants/torrentStatusMap.ts
Figured I'd just make a PR instead of asking in the issues. I've been wanting a way to filter out -arr added torrents if I tag them with "automated" or something. This doesn't allow the exclusion directly (seemed like overkill to make negated selections possible), but allows multiple tags, statuses, trackers to be selected with ctrl+click or shift+click to select a bunch (same logic as torrents list).
There's a little special logic for "all" and "untagged" type filters, but otherwise straightforward. Could probably be a bit briefer or more elegant, but it works. I wasn't sure if any of it should go in a utility file or something.
> Allow multiple selection on sidebar filters

- .github/workflows/translations.yml
The scheduled i18n sync workflow always fails on forks, this makes sure it is only run on jesec/flood.
> CI: make i18n sync workflow only run on main repo

- client/src/javascript/components/modals/feeds-modal/DownloadRulesTab.tsx
- client/src/javascript/components/modals/feeds-modal/FeedsTab.tsx
Due to text inputs retaining their state on component rerenders
editing the download rules and feeds forces previous values to be bound
to the newly edited rule/feed.
A new component instance is forced by keying the parent component
and thus the new defaultValue on inputs is taken into account
fixes #460
This is honestly a lazy fix, I think there could be other related issues to this due to the way `<form>` onSubmit is used and defaultValues on inputs to initialize them. Similar problems could arise anywhere else in the application where list-editing is handled in the same way, so I'd recommend a different aproach, but don't want to make too much of a mess.
> Force new component instance when editing download rules and feeds

- client/src/javascript/components/general/WindowTitle.tsx
- client/src/javascript/components/modals/settings-modal/UITab.tsx
- client/src/javascript/components/modals/settings-modal/lists/MiscUISettingsList.tsx
- client/src/javascript/i18n/strings/en.json
- shared/constants/defaultFloodSettings.ts
- shared/types/FloodSettings.ts
This PR adds a toggle under "User Interface" that toggles the display of upload and download speed in the page title.
> client: add page title speed display preference

- client/src/javascript/components/sidebar/Expando.tsx
- client/src/javascript/components/sidebar/StatusFilters.tsx
- client/src/javascript/components/sidebar/TagFilters.tsx
- client/src/javascript/components/sidebar/TrackerFilters.tsx
- client/src/sass/components/_sidebar-filter.scss
Makes sidebar filter sections collapseable by clicking the title. Since filter lists can get quite long, scrolling down to the tracker list or whichever can be tedious. Simple chevron/carat indicator hides filter section children.
> Make sidebar filter sections collapseable

- client/src/javascript/components/sidebar/TagFilters.tsx
- client/src/javascript/components/sidebar/TrackerFilters.tsx
Fixes regression introduced in #519 that prevented to reach the overview page when no torrent was present.
The changes are simply to make sur that the expand status hooks are defined before the related components can be returned.
#519 
Fix is for a change that is not yest part of a release
> Fix regression introduced in PR #519, fixes #522

- client/src/javascript/components/general/LinkedText.tsx
- client/src/javascript/components/modals/torrent-details-modal/TorrentGeneralInfo.tsx
- server/services/Deluge/clientGatewayService.ts
- server/services/Deluge/types/DelugeCoreMethods.ts
- server/services/Transmission/clientGatewayService.ts
- server/services/qBittorrent/clientGatewayService.ts
- server/services/rTorrent/clientGatewayService.ts
- server/services/rTorrent/constants/methodCallConfigs/torrentList.ts
- server/util/torrentFileUtil.ts
- shared/types/Torrent.ts
Mostly simple as it's supported by the various clients, except in the case of rtorrent.
For rtorrent, tags are stored in custom1, consistent with other clients. For that reason, comment is being stored in custom2,
which is also consistent with other clients. In particular, rutorrent uses a prefix on the comment for some reason, which is duplicated in this change to preserve cross-compatibility.
Also turns http: and https: text in comments into links, also consistent with other clients (and a main utility of having comments in the first place).
Fixes #435
> Added comment to torrent details

- server/services/torrentService.ts
> server: torrentService: normalize case of hash during torrent lookup

- server/services/qBittorrent/clientRequestManager.ts
The API endpoint for login changed in qBittorrent (violating semver).
This patch has been tested with qBittorrent 4.4.0 - 4.4.5.
#592
> Log into qBittorrent using HTTP-POST

- client/src/javascript/components/general/LinkedText.tsx
render line break in torrent comment
render `\n` as `<br />` and keep whitespace
> Fix torrent comment line break

- client/src/javascript/components/modals/torrent-details-modal/TorrentGeneralInfo.tsx
- server/services/rTorrent/constants/methodCallConfigs/torrentList.ts
There is no need to display trailing whitespaces, strip torrnet comment.
> Strip torrent comment

- client/src/javascript/components/torrent-list/TorrentList.tsx
- Feat: detects magnet links on paste, opens new torrent modal with link pre-filled
- #689 : Split this PR in-two
Detect magnet link in clipboard (CTRL+V) - if detected, open new torrent modal with link pre-filled:
> Detect magnet and torrent links from clipboard on paste

- client/src/javascript/components/sidebar/NotificationsButton.tsx
- client/src/javascript/components/sidebar/SidebarFilter.tsx
A couple react related fixes. One fixes a console error, the other an unwanted rendered result.
- Fix: `key={}` must be set on the rendered component (cannot be passed down and set within the component)
- Fix: conditional rendering via `&&` must be a conditional statement (not relying on value truthy/falsy) otherwise a `0` value will be rendered
- Using `!=` to fix instead of `!==` because it catches both `null` and `undefined` values
N/A
Before / After
> fix(client): react render logic

- server/bin/web-server.ts
close https://github.com/jesec/flood/issues/696
> fix(server): `@fastify/express` doesn't work with http2

- client/src/sass/components/_modals.scss
The modal was overflowing on mobile viewports following changes in https://github.com/jesec/flood/pull/597
This PR unsets the `min-width` for mobile viewports.
Fixes https://github.com/jesec/flood/issues/711
> Fix mobile modal overflow

- config.ts
- server/routes/api/index.ts
- server/routes/api/torrents.ts
- server/routes/utils.ts
- shared/schema/Config.ts
> feat: new args `--disable-rate-limit`

- server/services/qBittorrent/clientRequestManager.ts
Fixes add torrent files with no authentication using qbittorrent.
authCookie resolves to undefined when used without authentication. This lead to axios throwing ERR_HTTP_INVALID_HEADER_VALUE. Fixed to use the same method getRequestHeaders instead of the direct this.authCookie call, so it does not try to send the request with Cookie: undefined header.
> fix(qBittorrent): Add torrent files without authentication

- server/services/qBittorrent/clientRequestManager.ts
Flood is attempting to remove the tag `undefined` when it's suppose to be removing all tags.
#605 
Coalesce `undefined` to a blank string.
> Fix qBittorrent tag removal

- server/models/FeedReader.ts
Adds a user agent to the http call used to retrive rss feeds. This is needed because some rss servers refuses to answer if no user agent is set.
> Add a user agent for rss

- server/services/Deluge/clientRequestManager.ts
There currently is an issue with the concatenation of buffers in the `clientRequestManager.ts` of the Deluge service, more specifically at [L129](https://github.com/jesec/flood/blob/master/server/services/Deluge/clientRequestManager.ts#L129). If a client has a lot of torrents (in the current case, 588 torrents crash the software - though this is not the minimal amount to reproduce the issue), Flood will crash at boot up when it receives the packets from Deluge. Below is an explanation of the issue more specifically:
I have debugged the line to see what goes wrong. If you take a look at the first screenshot, you can see that `rpcBuffer.length = 16379`, `chunk.length = 16384` and `rpcBufferSize = 50328`. `rpcBuffer` is the content of the buffer currently in memory (captured from a previous …
> fix: correct buffers concatenation in the socket manager (Deluge)

- server/services/Transmission/clientGatewayService.ts
Transmission ratio calculation was based on ```torrent.uploadedEver/torrent.downloadedEver```, which caused some torrents not initiated in flood to have a ratio of -1.
The calculation is now based on ```torrent.uploadedEver / torrent.totalSize```
#720
Before change:
Note the ratio is -1
After change
Note the ratio is now correctly displayed: 0.01
> changed transmission ratio calculation to total size instead of downloaded size

- server/services/qBittorrent/clientRequestManager.ts
- server/services/qBittorrent/util/apiVersionCheck.ts
In qBittorrent 5.0.0 (webapi v2.11.0 and above) the method name for **pause** and **resume** torrent has been changed to **stop** and **start**. This fix check whether the webapi is 2.11 or above and if so it uses the correct method names.
https://github.com/jesec/flood/issues/800
> fix: #800 resume and pause does not work with qbittorrent 5

- server/services/qBittorrent/clientGatewayService.ts
- server/services/qBittorrent/clientRequestManager.ts
- server/services/qBittorrent/types/QBittorrentTorrentsMethods.ts
In Qbittorrent 5 and later the "add_paused" option is changed to "add_stopped". This fix checks the apiversion and uses the correct key.
Dynamically set add_paused or add_stopped depending on apiversion
> fix: add_paused changed to add_stopped in qbit 5

- server/services/qBittorrent/clientGatewayService.ts
- server/services/qBittorrent/clientRequestManager.ts
- server/services/qBittorrent/util/apiVersionCheck.ts
When Flood is started **before** a qBittorrent 5 client, starting and stopping torrents will fail due to the wrong method being called.
This is happening due to Flood getting the API Version in the clientRequestManager constructor ([clientRequestManager.ts#L626](https://github.com/jesec/flood/blob/843b9c966cabcbcc542210ee0d08c4262255278f/server/services/qBittorrent/clientRequestManager.ts#L626)) and nowhere else. If this request fails then the `apiVersion` will remain null until Flood is restarted.
I made the `apiVersion` consistent with the `authCookie` so that it's kept in sync with the qBittorrent client and can be awaited to ensure the value is resolved. I also renamed `updateAuthCookie` to `updateConnection` so that it better represents what the method is now doing.
As …
> fix(qBittorrent): API Version state handling

- server/services/rTorrent/util/XMLRPCSerializer.ts
I just happened to notice this while taking tcpdumps between flood and rTorrent, it doesn't appear to have an negative impact (both xmlrpc-c and tinyxml2 just ignore it), but I tracked it down out of curiosity.
Commands for testing:
```js
console.log(value(["foo", "bar"]));
console.log(sParams(["foo", "bar"]));
```
Before:
```
<value><array><data><value><string>foo</string></value>,<value><string>bar</string></value></data></array></value>
<params><param><value><string>foo</string></value></param>,<param><value><string>bar</string></value></param></params>
```
After:
```
<value><array><data><value><string>foo</string></value><value><string>bar</string></value></data></array></value>
<params><param><value><string>foo</string></value></param><param><value><string>bar</string></value></param> …
```
> fix(rTorrent): prevent extra commas in serialized XML

- server/models/Users.ts
- server/services/feedService.ts
- server/services/notificationService.ts
- server/services/settingService.ts
Run `nedb` compaction every `dbclean` interval. `nedb` only appends a deleted tag for data deletion, so deleting data won't shrink the on-disk datastore size. Compaction rewrites the entire DB into datastore.
This was originally intended to fix #399, #645, but that was apparently already fixed in af8de75e0593a48864d64c84c2e1c12d9ff0a7e1. However, it's still in theory for other datastores to write too much stuff into datastores (e.g. feed), so compaction after db cleanup should help.
#399, #645.
https://github.com/jesec/flood/issues/399#issuecomment-2241635132 also mentioned the transmission log, which doesn't seem to be managed by `nedb`. That is out-of-scope of this PR.
> Run compaction every `dbclean` interval

- server/services/index.ts
During user deletion, check if `userServiceInstance` is not `null` or `undefined` before deleting them. This can happen in cases such as migration (so the users are not yet loaded).
This was a cause of an old migration bug (#401, `userV1` -> `userV2`). I doubt if anyone is still using the v1 user format, but let's not be sorry.
Closes #401
> Check if user services is bootstrapped before removing instances

- .github/workflows/build.yml
- .github/workflows/publish-rolling.yml
- package.json
> build: replace deprecated `pkg` with `@yao-pkg/pkg`

- client/src/javascript/components/modals/settings-modal/BandwidthTab.tsx
I had this issue in the past which led me to find (and answer) the linked discussion page.
But I had the issue again today, so decided to implement a fix.
I considered adding translations for:
```
settings.bandwidth.transferrate.global.throttle.download
settings.bandwidth.transferrate.global.throttle.upload
```
For every language as some have their own preferred units of measure, but B/s seems fairly universal.
There was precedent for this change in [`client/src/javascript/components/modals/settings-modal/ResourcesTab.tsx`](https://github.com/jesec/flood/blob/master/client/src/javascript/components/modals/settings-modal/ResourcesTab.tsx)
#546
> Added units of measure to throttle speeds
