jesec/flood

server/tsconfig.json
While the README says flood only support the current version of NodeJS, the package.json indicates that NodeJS >= 12 is supposed to work.
This PR is a fix on the TS config to allow the transpiled code to run on version that doesn't support optional chaining. Cf https://github.com/jesec/flood/issues/44#issuecomment-703281963
The fix is based on Typescript documentation regarding the support of target and targeted NodeJS version: https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping
As explained in this issue Flood does compile on Node 12 but crashes at runtime because of the optional chaining.
In order to reproduce:
1. Use Node 12
2. Clone the repo
3. Build from the source
4. Launch Flood
While supporting the last version is a good thing, supporting at least the current LTS …
=> build: fix target version to support Node 12 & up

client/src/javascript/components/general/filesystem/FilesystemBrowserTextbox.tsx, client/src/javascript/components/modals/add-torrents-modal/AddTorrentsByFile.tsx, client/src/javascript/components/modals/add-torrents-modal/AddTorrentsByURL.tsx, client/src/javascript/i18n/strings.compiled.json, client/src/javascript/i18n/strings.json, server/routes/api/torrents.test.ts, server/routes/api/torrents.ts, server/services/rTorrent/clientGatewayService.ts, server/util/torrentFileUtil.ts, shared/types/TorrentFile.ts, shared/types/api/torrents.ts
=> feature: allow to add completed torrent without checking

client/src/javascript/components/general/form-elements/FilesystemBrowserTextbox.tsx, client/src/javascript/components/general/form-elements/TagSelect.tsx, client/src/javascript/components/modals/add-torrents-modal/AddTorrentsByFile.tsx, client/src/javascript/components/modals/add-torrents-modal/AddTorrentsByURL.tsx, client/src/javascript/components/torrent-list/TorrentList.tsx, client/src/javascript/util/userPreferences.ts, server/routes/api/index.test.ts, server/routes/api/torrents.ts, shared/types/FloodSettings.ts
https://github.com/jesec/flood/projects/5#card-43741338
=> feature: tag-specific download destination preference

server/services/qBittorrent/clientGatewayService.ts, server/services/qBittorrent/clientRequestManager.ts
This is done by first removing all tags then re-adding the correct tags.
Tested running qBittorrent v4.3.0 on linux.
=> Fixed removing tags in qbittorrent.

README.md
Adds minimum qbittorrent version to README
Fixes https://github.com/jesec/flood/issues/98#issue-747609196
API changes with different versions of qBittorrent. This gives a heads up to users that the app works on the current qBittorrent API.
=> Add qBittorrent versioning documentation

client/src/javascript/app.tsx, client/src/javascript/components/AppWrapper.tsx, client/src/javascript/components/general/ListViewport.tsx, client/src/javascript/components/icons/BaseIcon.tsx, client/src/javascript/components/icons/ThemeSwitchIcon.tsx, client/src/javascript/components/sidebar/Sidebar.tsx, client/src/javascript/components/sidebar/ThemeSwitchButton.tsx, client/src/javascript/i18n/strings.compiled.json, client/src/javascript/i18n/strings.json, client/src/javascript/stores/ConfigStore.ts, client/src/sass/tools/_themes.scss
=> feature: allow user to switch theme via a button

client/src/javascript/constants/Languages.ts
"nyelv" means language. But because it's a list of languages we don't need to say it again explicitly.
=> Fix hungarian language naming issue

client/src/javascript/actions/TorrentActions.ts, client/src/javascript/components/general/filesystem/DirectoryFileList.tsx, client/src/sass/components/_directory-tree.scss, server/routes/api/auth.test.ts, server/routes/api/auth.ts, server/routes/api/client.test.ts, server/routes/api/feed-monitor.test.ts, server/routes/api/index.test.ts, server/routes/api/index.ts, server/routes/api/torrents.test.ts, server/routes/api/torrents.ts, server/util/authUtil.ts, shared/schema/api/torrents.ts
Then, such a link can be consumed by a video player, which may support more formats and provide better experience than browsers. Users can also share or use the link for other purposes.
=> feature: allow to copy permalink of content

.gitignore
Can use a specific node version for development
=> fix: ignore .nvmrc file

client/src/javascript/components/sidebar/SidebarFilter.tsx, client/src/javascript/components/sidebar/TagFilters.tsx, client/src/javascript/components/sidebar/TrackerFilters.tsx, client/src/javascript/stores/TorrentFilterStore.ts, client/src/sass/components/_sidebar-filter.scss, server/services/taxonomyService.ts, shared/types/Taxonomy.ts
For https://github.com/jesec/flood/discussions/244
=> feat: display torrents size on sidebar

client/src/sass/components/_sidebar.scss
a regression from #369
Before
After
=> fix: disk usage width style

.github/workflows/publish-rolling.yml
=> ci: fix publish-rolling.yml

server/bin/web-server.ts
=> fix(server): handle number port

.github/workflows/publish-rolling.yml, package.json, server/config/webpack.config.prod.js
=> enable source map

.github/workflows/publish-rolling.yml, package.json, server/config/webpack.config.prod.js
=> Revert "enable source map"

package-lock.json, package.json
=> chore: upgrade tsx to v4.6.2

server/routes/api/torrents.ts
=> fix: `/metainfo` json response

server/routes/api/torrents.ts
=> fix: only generate mediainfo for video file

CHANGELOG.md, distribution/alpine/flood/APKBUILD, distribution/archlinux/flood/PKGBUILD, distribution/debian/flood-bin/BUILD, distribution/debian/flood/changelog, package-lock.json, package.json
=> bump: 4.8.1

.github/workflows/build.yml, .github/workflows/check.yml, .github/workflows/codeql-analysis.yml, .github/workflows/distribute-archlinux.yml, .github/workflows/distribute-debian.yml, .github/workflows/publish-rolling.yml, .github/workflows/release.yml, .github/workflows/test-backend.yml, .github/workflows/translations.yml
=> ci: upgrade deprecated actions and command

CHANGELOG.md, distribution/alpine/flood/APKBUILD, distribution/archlinux/flood/PKGBUILD, distribution/debian/flood-bin/BUILD, distribution/debian/flood/changelog, package-lock.json, package.json
=> bump: 4.8.2

.github/workflows/distribute-archlinux.yml, .github/workflows/publish-rolling.yml, .github/workflows/release.yml
=> ci: upgrade deprecated actions

distribution/containers/Dockerfile.distroless
=> build: should use `RUN cp` not `COPY`

server/services/Transmission/clientGatewayService.ts
fix https://github.com/jesec/flood/issues/762
=> fix(transmission): avoid set down/upload speed to 0

.npmrc
=> ci: fix publish

client/config/webpack.config.dev.js, client/config/webpack.config.prod.js
=> build: disable sass deprecated warning

Dockerfile
=> build: fix docker warn

package.json
=> bump: 4.8.3

package.json
=> bump: 4.8.4

server/services/rTorrent/util/XMLRPCDeserializer.ts
=> fix(rTorrent): support xmlrpc int type

package.json
=> release: 4.8.5

.github/workflows/distribute-debian.yml
=> ci: use bazel@7 to build deb

.github/workflows/distribute-debian.yml
=> ci: upload deb with gh cli to avoid override

.github/workflows/distribute-archlinux.yml, .github/workflows/distribute-debian.yml, distribution/archlinux/flood/PKGBUILD, distribution/debian/flood-bin/BUILD, distribution/debian/flood/control, package.json
=> release: 4.9.2

distribution/debian/flood/control, package.json
=> release: 4.9.3

.github/workflows/publish-rolling.yml, .github/workflows/release.yml
=> ci: replace apt with apt-get

package.json
=> release: 4.9.4

.github/workflows/release.yml
=> ci: use new pkg

package.json
=> release: 4.9.5

client/src/javascript/i18n/strings/es.json, client/src/javascript/i18n/strings/fr.json, client/src/javascript/i18n/strings/ro.json
=> i18n: new translations

package.json
=> release: 4.10.0
